// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.tsx";
import * as $api_image_uid_id_ from "./routes/api/image/[uid]/[id].tsx";
import * as $api_image_index from "./routes/api/image/index.tsx";
import * as $auth_oauth2callback from "./routes/auth/oauth2callback.ts";
import * as $auth_signin from "./routes/auth/signin.ts";
import * as $auth_signout from "./routes/auth/signout.ts";
import * as $image_uid_id_ from "./routes/image/[uid]/[id].tsx";
import * as $image_uid_index from "./routes/image/[uid]/index.tsx";
import * as $index from "./routes/index.tsx";
import * as $memo_id_ from "./routes/memo/[id].tsx";
import * as $memo_index from "./routes/memo/index.tsx";
import * as $new from "./routes/new.tsx";
import * as $ImageConvert from "./islands/ImageConvert.tsx";
import * as $TextArea from "./islands/TextArea.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.tsx": $_middleware,
    "./routes/api/image/[uid]/[id].tsx": $api_image_uid_id_,
    "./routes/api/image/index.tsx": $api_image_index,
    "./routes/auth/oauth2callback.ts": $auth_oauth2callback,
    "./routes/auth/signin.ts": $auth_signin,
    "./routes/auth/signout.ts": $auth_signout,
    "./routes/image/[uid]/[id].tsx": $image_uid_id_,
    "./routes/image/[uid]/index.tsx": $image_uid_index,
    "./routes/index.tsx": $index,
    "./routes/memo/[id].tsx": $memo_id_,
    "./routes/memo/index.tsx": $memo_index,
    "./routes/new.tsx": $new,
  },
  islands: {
    "./islands/ImageConvert.tsx": $ImageConvert,
    "./islands/TextArea.tsx": $TextArea,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
